events {}

http {
    server {
        listen 80;

        location /usuario/ {
            proxy_pass http://usuario:8000/;
        }

        location /estoque/ {
            proxy_pass http://estoque:8000/;
        }

        location /pedido/ {
            proxy_pass http://pedido:8000/;

        }
    }
}