events {}

http {
    server {
        listen 80;

        location /auth/validate {
            internal;
            proxy_pass http://auth-service:8000/validate;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Content-Length "";
            proxy_pass_request_body off;
        }

        location /auth/login {
            proxy_pass http://auth-service:8000/login;
        }

        location /payment/ {
            auth_request /auth/validate;
            error_page 401 = @unauthorized;
            proxy_pass http://payment-service:8000;
        }

        location /estoque/ {
            auth_request /auth/validate;
            error_page 401 = @unauthorized;
            proxy_pass http://estoque:8000;
        }

        location /pedido/ {
            auth_request /auth/validate;
            error_page 401 = @unauthorized;
            proxy_pass http://pedido_service:8000;
        }

        location @unauthorized {
            return 401 '{"detail": "Token inválido ou ausente"}';
            add_header Content-Type application/json;
        }
    }
}