events {}

http {
    server {
        listen 80;

        location = /auth {
            internal;
            proxy_pass http://auth-service:8000/validate;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Content-Length "";
            proxy_pass_request_body off;
        }

        location /auth/login {
            proxy_pass http://auth-service:8000/login;
        }

        location /payment/ {
            auth_request /auth;
            proxy_pass http://payment-service:8000;
            proxy_set_header X-User-Id $upstream_http_x_user_id;
        }

        location /estoque/ {
            auth_request /auth;
            proxy_pass http://estoque:8000;
            proxy_set_header X-User-Id $upstream_http_x_user_id;
        }

        location /pedidos/ {
            auth_request /auth;
            proxy_pass http://pedido_service:8000;
            proxy_set_header X-User-Id $upstream_http_x_user_id;
        }

        # Liberação dos Swaggers do FastAPI
        location /auth/docs {
            proxy_pass http://auth-service:8000/docs;
        }

        location /auth/openapi.json {
            proxy_pass http://auth-service:8000/openapi.json;
        }

        location /payment/docs {
            proxy_pass http://payment-service:8000/docs;
        }

        location /payment/openapi.json {
            proxy_pass http://payment-service:8000/openapi.json;
        }

        location /estoque/docs {
            proxy_pass http://estoque:8000/docs;
        }

        location /estoque/openapi.json {
            proxy_pass http://estoque:8000/openapi.json;
        }

        location /pedidos/docs {
            proxy_pass http://pedido_service:8000/docs;
        }

        location /pedidos/openapi.json {
            proxy_pass http://pedido_service:8000/openapi.json;
        }
    }
}