version: '3.8'

services:
  estoque-db:
    image: postgres:16
    container_name: estoque-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estoque
    ports:
      - "5433:5432"
    volumes:
      - estoque_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estoque"]
      interval: 5s
      timeout: 5s
      retries: 5

  estoque:
    build: ./services/estoque
    container_name: estoque
    ports:
      - "5003:8000"
    secrets:
      - public_key
    environment:
      PUBLIC_KEY_PATH: /run/secrets/public_key
      DATABASE_URL: postgresql://postgres:postgres@estoque-db:5432/estoque
    depends_on:
      estoque-db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: estoque-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - estoque-db

volumes:
  estoque_data:

secrets:
  private_key:
    file: ./keys/private_key.pem
  public_key:
    file: ./keys/public_key.pem