version: "3.9"

services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5000:8000"
    secrets:
      - private_key
    environment:
      PRIVATE_KEY_PATH: /run/secrets/private_key

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "5001:8000"
    secrets:
      - public_key
    environment:
      PUBLIC_KEY_PATH: /run/secrets/public_key

  estoque:
    build: ./services/estoque
    container_name: estoque
    ports:
      - "5003:8000"
    secrets:
      - public_key
    environment:
      PUBLIC_KEY_PATH: /run/secrets/public_key

  pedido:
    build: ./services/pedido
    container_name: pedido
    ports:
      - "5004:8000"
    secrets:
      - public_key

  nginx:
    build: ./api-gateway
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - payment-service
      - estoque
      - pedido

secrets:
  private_key:
    file: ./keys/private_key.pem
  public_key:
    file: ./keys/public_key.pem
