services:
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "5001:8000"
    secrets:
      - private_key
    environment:
      PRIVATE_KEY_PATH: /run/secrets/private_key

  # INíCIO - Microsserviço de pagamento
  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "5002:8000"
    secrets:
      - public_key
    environment:
      PUBLIC_KEY_PATH: /run/secrets/public_key
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - payment-postgres

  payment-postgres:
    image: postgres:18.3-alpine
    container_name: payment-db
    restart: always
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: payments
    volumes:
      - payment_postgres_data:/var/lib/postgresql

  # FIM - Microsserviço de pagamento

  # API_Gateway
  nginx:
    build: ./api-gateway
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - payment-service
      - payment-postgres

  rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Painel de gestão
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  estoque-db:
    image: postgres:16
    container_name: estoque-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estoque
    ports:
      - "5433:5432"
    volumes:
      - estoque_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estoque"]
      interval: 5s
      timeout: 5s
      retries: 5

  estoque:
    build: ./services/estoque
    container_name: estoque
    ports:
      - "5003:8000"
    secrets:
      - public_key
    environment:
      PUBLIC_KEY_PATH: /run/secrets/public_key
      DATABASE_URL: postgresql://postgres:postgres@estoque-db:5432/estoque
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/ 
    depends_on:
      estoque-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4
    container_name: estoque-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - estoque-db

  pedido-db:
    image: postgres:16
    container_name: pedido_db
    environment:
      POSTGRES_USER: pedido_user
      POSTGRES_PASSWORD: pedido_pass
      POSTGRES_DB: pedido_db
    ports:
      - "5435:5432"
    volumes:
      - pedido_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedido_user -d pedido_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  pedido:
    build: ./services/pedido
    container_name: pedido_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://pedido_user:pedido_pass@pedido-db:5432/pedido_db # era @db:
      USE_MOCK: "true"
      DISABLE_AUTH: "true"
      AUTO_APPROVE: "false"
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    depends_on:
      pedido-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  payment_postgres_data:
  estoque_data:
  pedido_pgdata:

secrets:
  private_key:
    file: ./keys/private_key.pem
  public_key:
    file: ./keys/public_key.pem
  postgres_user:
    file: ./keys/postgres_user.txt
  postgres_password:
    file: ./keys/postgres_password.txt
