apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: estoque-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: estoque.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: estoque
                port:
                  number: 8000
