apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  labels:
    app: auth-service
type: Opaque
data:
  JWT_SECRET: ZTM5ODMyMjJmM2VhNTU0ODE0MzdkNmQ2NDEzYzQ2YTg0MGE5NDI4MzA0Y2I4NzljYThkNDQ2YmM4MzM3Y2I4NQ==
