apiVersion: v1
kind: Service
metadata:
  name: estoque-db
  labels:
    app: estoque-db
spec:
  selector:
    app: estoque-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
