apiVersion: v1
kind: ConfigMap
metadata:
  name: pedido-service-config
  labels:
    app: pedido-service
data:
  USE_MOCK: "false"
  DISABLE_AUTH: "false"
  AUTO_APPROVE: "false"
  DATABASE_URL: "postgresql://pedido_user:pedido_pass@pedido-db:5432/pedido_db"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"