apiVersion: v1
kind: Secret
metadata:
  name: pedido-db-secret
  labels:
    app: pedido-db
type: Opaque
data:
  POSTGRES_USER: cGVkaWRvX3VzZXI=
  POSTGRES_PASSWORD: cGVkaWRvX3Bhc3M=
  POSTGRES_DB: cGVkaWRvX2Ri