apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-db
  labels:
    app: pedido-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pedido-db
  template:
    metadata:
      labels:
        app: pedido-db
    spec:
      containers:
        - name: pedido-db
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pedido-db-secret
          volumeMounts:
            - name: pedido-db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "pedido_user", "-d", "pedido_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "pedido_user", "-d", "pedido_db"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      volumes:
        - name: pedido-db-data
          persistentVolumeClaim:
            claimName: pedido-db-pvc