sonar.projectKey=GuilhermeRode_estoque-service
sonar.organization=guilhermerode

sonar.projectName=Estoque Service
sonar.projectVersion=1.0

# Caminho do código fonte (relativo a este arquivo)
sonar.sources=app
sonar.tests=tests

# Cobertura de testes gerada pelo pytest
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

# Exclusões
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/migrations/**
