sonar.projectKey=auth-service-qF8mN2vK7pX4rT9wY3cH6jL1bD5sZ8u
sonar.organization=jeancarlosrothenburg

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13.5
sonar.sourceEncoding=UTF-8