name: Auth-Service - CI/CD Pipeline
on:
  push:
    branches:
      - main
      - develop
      - feature/**
    paths:
      - "services/auth-service/**"

  pull_request:
    branches:
      - main
      - develop
    paths:
      - "/services/auth-service/**"

jobs:
  auth-service:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: services/auth-service

    env:
      PYTHONPATH: .
      JWT_SECRET: 7f3c9a2d5e8b4c1f6a9d2e7c0b3f8a5d9e2c6b1f4a7d0e3c9b6f2a8d5e1c7b3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Docker login
        env:
          AUTH_SERVICE_DOCKER_USERNAME: ${{ secrets.AUTH_SERVICE_DOCKER_USERNAME }}
          AUTH_SERVICE_DOCKER_PASSWORD: ${{ secrets.AUTH_SERVICE_DOCKER_PASSWORD }}
        run: |
          echo "USER=${{ secrets.AUTH_SERVICE_DOCKER_USERNAME }}"
          echo "PASS length=${#AUTH_SERVICE_DOCKER_PASSWORD}"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements.txt

      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=xml

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: services/auth-service
        env:
          SONAR_TOKEN: ${{ secrets.AUTH_SERVICE_SONAR_KEY }}

      - name: Docker Image build
        run: docker build -t auth-service .

      - name: Docker Hub authentication
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AUTH_SERVICE_DOCKER_USERNAME }}
          password: ${{ secrets.AUTH_SERVICE_DOCKER_PASSWORD }}

      - name: Docker Image push (DEV)
        if: github.ref == 'refs/heads/develop'
        run: |
          docker tag auth-service ${{ secrets.AUTH_SERVICE_DOCKER_USERNAME }}/auth-service:dev
          docker push ${{ secrets.AUTH_SERVICE_DOCKER_USERNAME}}/auth-service:dev

      - name: Docker Image push (HOMOL)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag auth-service ${{ secrets.AUTH_SERVICE_DOCKER_USERNAME }}/auth-service:latest
          docker push ${{ secrets.AUTH_SERVICE_DOCKER_USERNAME }}/auth-service:latest

      - name: Deploy (DEV)
        if: github.ref == 'refs/heads/develop'
        run: curl ${{ secrets.AUTH_SERVICE_RENDER_DEPLOY_HOOK_DEV }}

      - name: Deploy (HOMOL)
        if: github.ref == 'refs/heads/main'
        run: curl ${{ secrets.AUTH_SERVICE_RENDER_DEPLOY_HOOK_HOMOL }}
